apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deploy
  labels:
    app: myapp
spec:
  selector:
    matchLabels:
      env: dev-deploy
  replicas: 4
  template:
    metadata: 
      name: myapp-pod
      labels: 
        app: myapp
        env: dev-deploy
    spec:
      containers:
        - name: nginx-controller
          image: nginx
    