apiVersion: v1
kind: Pod
metadata:
  name: db-pod
  labels:
    name: db-pod
    app: db
spec:
  containers:
    - name: db
      image: postgres:11-alpine
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_HOST_AUTH_METHOD
          value: trust