apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app-deploy
  labels:
    name: result-app-pod
    app: result-app
spec:
  selector:
    matchLabels:
      name: result-app-pod
      app: result-app
  replicas: 2
  template:
    metadata:
      name: result-app-pod
      labels:
        name: result-app-pod
        app: result-app
    spec:
      containers:
        - name: result-app
          image: eesprit/voting-app-result
          ports:
            - containerPort: 80
      
    