apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-deploy
  labels:
    name: voting-app-pod
    app: voting-app
spec:
  selector:
    matchLabels:
      name: voting-app-pod
      app: voting-app
  replicas: 2
  template:
    metadata: 
      name: voting-app-pod
      labels: 
        name: voting-app-pod
        app: voting-app
    spec:
      containers:
      - name: voting-app
        image: eesprit/voting-app-vote
        ports:
        - containerPort: 80
      
    